spring:
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  application:
    name: momogo-batch
  profiles:
    active: dev
    group:
      dev:
        - dev
      prod:
        - prod

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  batch:
    job:
      enabled: false

server:
  port: 8082

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL:admin@admin.com}
  file:
    base-url: ${APP_FILE_BASE_URL:http://localhost:8080/uploads}
    upload:
      allowed-extensions: jpg,jpeg,png,webp
      allowed-mime-types: image/jpeg,image/png,image/webp

