spring:
  threads:
    virtual:
      enabled: true
  application:
    name: momogo-api
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: momogo-api
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.momogo.core.domain.*
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev # 기본 활성화 프로필
    group:
      dev:
        - dev
      prod:
        - prod

#  gemini로 전환하기 위해 임시로 교체
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY:dummy-key}
#      chat:
#        options:
#          model: gpt-4o-mini
#          temperature: 0.7 # 응답의 다양성 값
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:dummy-key}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.7

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 3000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          # 카카오 registration 추가
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오가 제공하는 고유 회원식별자 키 이름 (Integer id)
jwt:
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    exp: ${JWT_ACCESS_TOKEN_EXP}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    exp: ${JWT_REFRESH_TOKEN_EXP}
    cookie:
      secure: ${JWT_REFRESH_COOKIE_SECURE}
      same-site: ${JWT_REFRESH_COOKIE_SAME_SITE}

app:
  storage:
    type: ${APP_STORAGE_TYPE:local}
  aws:
    s3-bucket: ${AWS_S3_BUCKET:momogo-s3}
    region: ${AWS_REGION:ap-northeast-2}
  super-admin:
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}
    name: ${SUPER_ADMIN_NAME}
  jwt:
    registry: redis
    max-active-count: 1
  file:
    # 클라이언트용 웹 서비스 URL 주소
    base-url: ${APP_FILE_BASE_URL}
    upload:
      allowed-extensions: jpg,jpeg,png,webp
      allowed-mime-types: image/jpeg,image/png,image/webp
      max-mark-size: 10MB
      # 물리 디스크 저장 경로
      dir: ${APP_FILE_UPLOAD_DIR}
  oauth2:
    success-redirect-url: ${OAUTH2_SUCCESS_REDIRECT_URL}
    failure-redirect-url: ${OAUTH2_FAILURE_REDIRECT_URL}

server:
  port: 8080
