-- 1. 공간 테이블 (유저가 참조해야 하므로 가장 먼저 생성)
CREATE TABLE "TBL_SPACE" (
	"id"	UUID		NOT NULL,
	"name"	VARCHAR(255)		NOT NULL,
	"description"	TEXT		NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	"updated_at"	TIMESTAMPTZ		NULL,
	CONSTRAINT "PK_TBL_SPACE" PRIMARY KEY ("id")
);

-- 2. 사용자 테이블
CREATE TABLE "TBL_USER" (
	"id"	UUID		NOT NULL,
	"space_id"	UUID		NULL,
	"password"	VARCHAR(255)		NOT NULL,
	"name"	VARCHAR(100)		NOT NULL,
	"email"	VARCHAR(255)		NOT NULL,
	"profile_image_url"	VARCHAR(500)		NULL,
	"role"	VARCHAR(50)		NOT NULL, -- SUPER_ADMIN, ADMIN, USER
	"social"	VARCHAR(50)		NULL,
	"is_banned"	BOOLEAN	DEFAULT FALSE	NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	"updated_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_USER" PRIMARY KEY ("id")
);

-- 3. 문제 카테고리 테이블
CREATE TABLE "TBL_PROBLEM_CATEGORY" (
	"id"	UUID		NOT NULL,
	"space_id"	UUID		NOT NULL,
	"name"	VARCHAR(100)		NOT NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_PROBLEM_CATEGORY" PRIMARY KEY ("id")
);

-- 4. 문제 메타데이터 테이블
CREATE TABLE "TBL_PROBLEM" (
	"id"	UUID		NOT NULL,
	"category_id"	UUID		NOT NULL,
	"name"	VARCHAR(255)		NOT NULL,
	"content"	TEXT		NOT NULL,
	"explanation"	TEXT		NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	"updated_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_PROBLEM" PRIMARY KEY ("id")
);

-- 5. 문제 통계 테이블 (1:1 구조)
CREATE TABLE "TBL_PROBLEM_COUNTERS" (
	"problem_id"	UUID		NOT NULL,
	"solved_count"	INTEGER	DEFAULT 0	NULL,
	"try_count"	INTEGER	DEFAULT 0	NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_PROBLEM_COUNTERS" PRIMARY KEY ("problem_id")
);

-- 6. 실시간 시험 방 테이블
CREATE TABLE "TBL_ROOM" (
	"id"	UUID		NOT NULL,
	"space_id"	UUID		NOT NULL,
	"name"	VARCHAR(50)		NULL,
	"description"	VARCHAR(255)		NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	"updated_at"	TIMESTAMPTZ		NULL,
	CONSTRAINT "PK_TBL_ROOM" PRIMARY KEY ("id")
);

-- 7. 방-문제 중간 테이블
CREATE TABLE "TBL_ROOM_PROBLEM" (
	"id"	UUID		NOT NULL,
	"room_id"	UUID		NOT NULL,
	"problem_id"	UUID		NOT NULL,
	"problem_order"	INTEGER		NOT NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_ROOM_PROBLEM" PRIMARY KEY ("id")
);

-- 8. 개인별 문제 풀이 이력 테이블 (복합 기본키 적용)
CREATE TABLE "TBL_USER_PROBLEM" (
	"user_id"	UUID		NOT NULL,
	"problem_id"	UUID		NOT NULL,
	"is_solved"	BOOLEAN		NOT NULL,
	"user_answer"	TEXT		NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_USER_PROBLEM" PRIMARY KEY ("user_id", "problem_id")
);

-- 9. 알림 테이블
CREATE TABLE "TBL_NOTIFICATION" (
	"id"	UUID		NOT NULL,
	"receiver_id"	UUID		NOT NULL,
	"title"	VARCHAR(255)		NOT NULL,
	"content"	TEXT		NOT NULL,
	"is_confirmed"	BOOLEAN	DEFAULT FALSE	NULL,
	"created_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	"updated_at"	TIMESTAMPTZ	DEFAULT CURRENT_TIMESTAMP	NULL,
	CONSTRAINT "PK_TBL_NOTIFICATION" PRIMARY KEY ("id")
);


-- ----------------------------------------------------
-- 외래키(FOREIGN KEY) 제약 조건 추가 (관계선 연결)
-- ----------------------------------------------------

ALTER TABLE "TBL_USER" ADD CONSTRAINT "FK_TBL_SPACE_TO_TBL_USER" FOREIGN KEY ("space_id") REFERENCES "TBL_SPACE" ("id");
ALTER TABLE "TBL_PROBLEM_CATEGORY" ADD CONSTRAINT "FK_TBL_SPACE_TO_TBL_PROBLEM_CATEGORY" FOREIGN KEY ("space_id") REFERENCES "TBL_SPACE" ("id");
ALTER TABLE "TBL_PROBLEM" ADD CONSTRAINT "FK_TBL_PROBLEM_CATEGORY_TO_TBL_PROBLEM" FOREIGN KEY ("category_id") REFERENCES "TBL_PROBLEM_CATEGORY" ("id");
ALTER TABLE "TBL_PROBLEM_COUNTERS" ADD CONSTRAINT "FK_TBL_PROBLEM_TO_TBL_PROBLEM_COUNTERS" FOREIGN KEY ("problem_id") REFERENCES "TBL_PROBLEM" ("id") ON DELETE CASCADE;
ALTER TABLE "TBL_ROOM" ADD CONSTRAINT "FK_TBL_SPACE_TO_TBL_ROOM" FOREIGN KEY ("space_id") REFERENCES "TBL_SPACE" ("id");
ALTER TABLE "TBL_ROOM_PROBLEM" ADD CONSTRAINT "FK_TBL_ROOM_TO_TBL_ROOM_PROBLEM" FOREIGN KEY ("room_id") REFERENCES "TBL_ROOM" ("id") ON DELETE CASCADE;
ALTER TABLE "TBL_ROOM_PROBLEM" ADD CONSTRAINT "FK_TBL_PROBLEM_TO_TBL_ROOM_PROBLEM" FOREIGN KEY ("problem_id") REFERENCES "TBL_PROBLEM" ("id");
ALTER TABLE "TBL_USER_PROBLEM" ADD CONSTRAINT "FK_TBL_USER_TO_TBL_USER_PROBLEM" FOREIGN KEY ("user_id") REFERENCES "TBL_USER" ("id");
ALTER TABLE "TBL_USER_PROBLEM" ADD CONSTRAINT "FK_TBL_PROBLEM_TO_TBL_USER_PROBLEM" FOREIGN KEY ("problem_id") REFERENCES "TBL_PROBLEM" ("id");
ALTER TABLE "TBL_NOTIFICATION" ADD CONSTRAINT "FK_TBL_USER_TO_TBL_NOTIFICATION" FOREIGN KEY ("receiver_id") REFERENCES "TBL_USER" ("id");
